---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "phpcs.xml"
      ignore_warnings: true
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
ratings:
  paths:
  - "src/**.php"
exclude_paths:
- "tests/*"
- "vendor/*"